  name: pure_tube_cast
  description: "YouTube caster for old devices"
  publish_to: 'none'

  version: 1.17.1+1

  environment:
    sdk: ^3.5.3

  dependencies:
    flutter:
      sdk: flutter

    youtube_explode_dart: ^2.0.2
    upnp_client: ^1.0.1
    xml: ^6.3.0
    receive_sharing_intent: ^1.8.1
    shared_preferences: ^2.2.2
    cupertino_icons: ^1.0.8
    http: ^1.2.0
    url_launcher: ^6.2.0
    html: ^0.15.4
    multicast_dns: ^0.3.3

    # ADB接続用パッケージ
    flutter_adb: ^0.1.1

    # 暗号化ライブラリ (flutter_adbが内部で使用)
    pointycastle: ^3.7.3
    path_provider: ^2.1.2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    uses-material-design: true